require_relative '../node_modules/react-native/scripts/react_native_pods'

# Enable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

target 'KidSpeak' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'KidSpeakTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )

    # Note: Header search path for React Native AppDelegate headers needs to be added manually in Xcode:
    # Build Settings > Header Search Paths > Add: $(SRCROOT)/../node_modules/react-native/Libraries/AppDelegate
    
    # Ensure Release builds are stripped and post-processed to avoid
    # large embedded frameworks inflating the final .app size.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        next unless config.name == 'Release'
        config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'YES'
        config.build_settings['STRIP_DEBUG_SYMBOLS_DURING_COPY'] = 'YES'
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['DEPLOYMENT_POSTPROCESSING'] = 'YES'
      end
    end
  end
end
